### PR TITLE
Backport chunk update threads and deferred chunk update options

### PR DESCRIPTION
**Pull request by embeddedt**
These options can significantly improve performance on lower-end systems. The logic for these was directly taken from the newer branches.

### CODE REVIEW

**Comment by Asek3** [comment]
Thanks for great work! However, I think it's better to use Modrinth's maven instead of CurseMaven, cuz of better readability of script.
Also, due to number of elements in "Advanced" tab we have issue on 4 GUI scale, maybe it's better to create new tab?
image

**Comment by IMS212** [comment]
The whole performance tab should be backported if this is going to be merged, as it's much easier for users.

**Comment by embeddedt** [comment]
> I think it's better to use Modrinth's maven instead of CurseMaven, cuz of better readability of script.

I would also prefer to use it but not all dependencies have 1.16 versions on Modrinth (at least Flywheel does not).

> maybe it's better to create new tab?

I agree; I will do that.

> The whole performance tab should be backported if this is going to be merged, as it's much easier for users.

I would prefer to minimize the scope of the changes and this would require implementing logic to migrate settings from the advanced to performance category.

**Comment by Asek3** [comment]
Good work, thx!

**Pull request merged**
